### ISSUE TITLE
Port 3 VLAN not seen on quad port intel

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#137]
Port 3 is not showing VLANs for the quad port test case.  Port setup is as follows:
- Port 1 is used for public
- Port 2 and 3 are assigned VLANs and used for test traffic
- Port 4 is left unused

After assigning vlan1 to port 1 and vlan2 to port 2  on the host we see
- vlan1 on port 1 - expected
- no vlan on port 2 - unexpected

Tasks:
- [x] debug why vlan is not seen on port 2
- [x] document issue and fix

**Comment by michaelspedersen** [comment]
Looks like the ports on Quad1,2 were misconfigured.
Both VLANs were assigned to Port 2 (trunk), but none were assigned to Port 3

I've updated the configuration as follows:
* Port 2: VLAN 1076
* Port 3: VLAN 1078

Did a quick test on Quad3,4 and here I was able to ping between nodes through port 2 and 3 (both configured with access VLANs).

I have not tested Quad1,2, since I can see some work has been done there already. I'll wait for Peter to verify before closing the issue.

**Comment by pmikus** [comment]
No it not working. It seems no traffic is not reaching quad2

**Comment by michaelspedersen** [comment]
Issue should be solved now. Infrastructure was expecting untagged traffic (no VLANs - Handled by access ports), while we were sending and expecting to receive tagged traffic.

I'll let Peter verify and we can update the issue from there.

**Comment by michaelspedersen** [comment]
Let's close this one out - We can create new issues/tasks for follow up as needed.
