### ISSUE TITLE
[KubeCon18] Benchmark 3 Service Densities of the Snake and Pipeline test cases on K8s

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#159]
Run benchmark tests and add the results to this ticket.  All tests will be run against a K8s worker node.

- [x] K8s Mellanox Pipeline (CSP) 
   - [x] 3 Chains, 1 NF
   - [x] 3 Chains, 2 NFs
   - [x] 2 Chains, 3 NFs
- [x] K8s Mellanox Snake Test (CSC)
   - [x] 3 Chains, 1 NF
   - [x] 3 Chains, 2 NFs
   - [x] 2 Chains, 3 NFs
- [x] K8s Intel  Pipeline Test (CSP)
   - [x] 3 Chains, 1 NF
   - [x] 3 Chains, 2 NFs
   - [x] 2 Chains, 3 NFs
- [x] K8s Intel Snake Test (CSC)
   - [x] 3 Chains, 1 NF
   - [x] 3 Chains, 2 NFs
   - [x] 2 Chains, 3 NFs

**Comment by michaelspedersen** [comment]
## Result matrices
All benchmarks are done with a 2 core (4 thread) host VPP configuration. Memif interfaces are configured with 1 RX queue, which adds the following requirements for an ideal distribution of queues in host VPP
- CSP: Number of chains must be modulo 2
- CSC: Total number of NFs must be modulo 2

All results that are non-ideal are marked with `*`. Results for 1c3n have also not been collected for this reason, and this is shown as `////` instead of a results.

All benchmarks are performed as MRR (Maximum Receive Rate) at 10Gbps, using 64B packets transmitted for 60 seconds.

```
  K8s, MLX (Packet.net), CSP
  CSP   001   002   003   004   006
  001*  2.73  2.71  ////   2.67  2.45
  002   5.30  5.08  5.16  ----  ----
  003*  5.04  4.96  ----  ----  ----
  004   5.06  ----  ----  ----  ----
  006   4.97  ----  ----  ----  ----
```

```
  K8s, MLX (Packet.net), CSC
  CSP   001   002   003   004   006
  001   3.03* 3.04  ////* 1.96  1.54
  002   5.33  3.54  3.17  ----  ----
  003   5.08* 3.89  ----  ----  ----
  004   5.09  ----  ----  ----  ----
  006   5.01  ----  ----  ----  ----
```

```
  K8s, Intel (Packet.net), CSP
  CSP   001   002   003   004   006
  001*  5.87  5.61  ////  5.33  5.14
  002   9.70  9.56  9.09  ----  ----
  003*  9.10  8.78  ----  ----  ----
  004   9.26  ----  ----  ----  ----
  006   9.07  ----  ----  ----  ----
```

```
  K8s, Intel (Packet.net), CSC
  CSP   001   002   003   004   006
  001   5.94* 4.73  ////* 2.81  1.95
  002   9.62  5.65  4.30  ----  ----
  003   8.90* 5.97  ----  ----  ----
  004   9.20  ----  ----  ----  ----
  006   9.03  ----  ----  ----  ----
```
