### ISSUE TITLE
Create vBNG virtual machine for KVM

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#31]
_Goal: vBNG VNF VM for KVM_

Tasks:
---
- [x]  Update vBNG build/runtime code to omit the need for vAAA  and vDHCP
  - [x] vAAA dependent code removed
  - [x] vDHCP dependent code removed
- [x]  DEFERRED: Investigate PCI pass-through (if large effort, create a new ticket)
   *  SR-IOV or Passthrough Mode
   * DEFERRING.  Will do another round of tests after this is figured out.
- [x] Update original vBNG install/build to work in KVM/vagrant environment
- [x]  Bring up vBNG VM on VM runtime (eg. libvirt + KVM)
- [x]  Create smoke test vm for checking packets pass through the BNG VM
- [x]  DEFERRED: Save VM with vBNG software installed
  - [ ]  If needed, Update scripts/vagrant config for using a saved vm
  - [ ] Document saving of vBNG VM (if anything is not generic)
  - [ ] Create minimal script for saving vBNG VM
- [x]  Validate test requirements
   - [x] Investigate need for vxlan
   - [x] investigate VMs required for testing

**Comment by michaelspedersen** [comment]
Investigate PCI pass-through:
- Put on hold for now
- We will likely create a separate ticket for this at a later time
- Does not work well with Mellanox Connectx-3
- Not yet tested with Mellanox Connectx-4

Save VM with vBNG software installed:
- Not yet done
- Idea is to create a common VPP image
- Currently vBNG functionality is added through a few lines of VPP configuration

Validate test requirements:
- VXLAN not needed yet (box-by-box).
- Current solution uses UDP packets (IPv4)
- 2 VMs requires: vBNG and Pktgen (since we don't need VXLAN)

**Comment by taylor** [comment]
DEFERRED: Save VM with vBNG software installed
  - [ ]  If needed, Update scripts/vagrant config for using a saved vm
  - [ ] Document saving of vBNG VM (if anything is not generic)
  - [ ] Create minimal script for saving vBNG VM


Will create another ticket for a base VPP VM as well as an additional ticket for saving the vBNG VM
